default_bonds = {
   'Ac': ['O', 'F', 'Cl', 'Br'],
   'Ag': ['O', 'S', 'F', 'Cl', 'Br', 'I', 'Se', 'Te', 'N', 'P', 'As', 'H'],
   'Al': ['O', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'N', 'P', 'As', 'H'],
   'Am': ['O', 'F', 'Cl', 'Br'],
   'As': ['S', 'Se', 'O', 'Te', 'F', 'Cl', 'Br', 'I', 'C'],
   'Au': ['Cl', 'I', 'O', 'S', 'F', 'Br', 'N', 'Se', 'Te', 'P', 'As', 'H'],
   'B': ['O', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'N', 'P', 'As', 'H', 'B'],
   'Ba': ['O', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'N', 'P', 'As', 'H'],
   'Be': ['O', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'N', 'P', 'As', 'H'],
   'Bi': ['O', 'S', 'Se', 'F', 'Cl', 'Br', 'I', 'N', 'Te', 'P', 'As', 'H'],
   'Bk': ['O', 'F', 'Cl', 'Br'],
   'Br': ['O', 'F', 'Cl'],
   'C': ['O', 'Cl', 'C', 'S', 'F', 'Br', 'N', 'Se', 'I', 'Te', 'P', 'H'],
   'Ca': ['O', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'N', 'P', 'As', 'H'],
   'Cd': ['O', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'N', 'P', 'As', 'H'],
   'Ce': ['O', 'S', 'F', 'Cl', 'Br', 'I', 'N', 'Se', 'Te', 'P', 'As', 'H'],
   'Cf': ['O', 'F', 'Cl', 'Br'],
   'Cl': ['O', 'F', 'Cl'],
   'Cm': ['O', 'F', 'Cl'],
   'Co': ['H', 'O', 'S', 'F', 'Cl', 'N', 'C', 'Br', 'I', 'Se', 'Te', 'P', 'As'],
   'Cr': ['O', 'F', 'Cl', 'Br', 'I', 'N', 'S', 'Se', 'Te', 'P', 'As', 'H'],
   'Cs': ['O', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'N', 'P', 'As', 'H'],
   'Cu': ['O', 'S', 'Se', 'F', 'Cl', 'Br', 'I', 'N', 'P', 'As', 'C', 'Te', 'H'],
   'Dy': ['O', 'F', 'Cl', 'Br', 'I', 'S', 'Se', 'Te', 'N', 'P', 'As', 'H'],
   'Er': ['O', 'S', 'Se', 'F', 'Cl', 'Br', 'I', 'Te', 'N', 'P', 'As', 'H'],
   'Es': ['O'],
   'Eu': ['O', 'S', 'F', 'Cl', 'Br', 'I', 'N', 'Se', 'Te', 'P', 'As', 'H'],
   'Fe': ['O', 'S', 'F', 'Cl', 'Br', 'I', 'N', 'C', 'Se', 'Te', 'P', 'As', 'H'],
   'Ga': ['Se', 'O', 'S', 'F', 'Cl', 'Br', 'I', 'Te', 'N', 'P', 'As', 'H'],
   'Gd': ['O', 'F', 'S', 'Cl', 'Br', 'I', 'Se', 'Te', 'N', 'P', 'As', 'H'],
   'Ge': ['O', 'S', 'Se', 'F', 'Cl', 'Br', 'I', 'Te', 'N', 'P', 'As', 'H', 'Ge'],
   'O': ['H', 'D', 'O'],
   'H': ['O', 'F', 'Cl', 'N'],
   'D': ['O', 'F', 'Cl', 'N'],
   'Hf': ['F', 'O', 'Cl', 'Br', 'S', 'Se', 'Te', 'I', 'N', 'P', 'As', 'H'],
   'Hg': ['O', 'F', 'Cl', 'S', 'Br', 'I', 'Se', 'Te', 'N', 'P', 'As', 'H', 'Hg'],
   'Ho': ['O', 'S', 'F', 'Cl', 'Br', 'I', 'Se', 'Te', 'N', 'P', 'As', 'H'],
   'I': ['I', 'F', 'Cl', 'O'],
   'In': ['Cl', 'O', 'S', 'F', 'Br', 'I', 'Co', 'Mn', 'Se', 'Te', 'N', 'P', 'As', 'H'],
   'Ir': ['O', 'F', 'Cl', 'S', 'Se', 'Te', 'Br', 'I', 'N', 'P', 'As', 'H'],
   'K': ['O', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'N', 'P', 'As', 'H'],
   'Kr': ['F'],
   'La': ['O', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'N', 'P', 'As', 'H'],
   'Li': ['O', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'N'],
   'Lu': ['O', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'N', 'P', 'As', 'H'],
   'Mg': ['O', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'N', 'P', 'As', 'H'],
   'Mn': ['O', 'S', 'F', 'Cl', 'Br', 'I', 'N', 'Se', 'Te', 'P', 'As', 'H'],
   'Mo': ['S', 'Cl', 'O', 'F', 'Br', 'N', 'I', 'Se', 'Te', 'P', 'As', 'H'],
   'N': ['O', 'F', 'Cl', 'N'],
   'Na': ['O', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'N', 'P', 'As', 'H'],
   'Nb': ['O', 'F', 'Cl', 'Br', 'N', 'I', 'S', 'Se', 'Te', 'P', 'As', 'H'],
   'Nd': ['O', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'N'],
   'NH': ['O', 'F', 'Cl'],
   'Ni': ['O', 'S', 'F', 'Cl', 'Br', 'I', 'N', 'Se', 'Te', 'P', 'As', 'H'],
   'Np': ['F', 'Cl', 'S', 'Br', 'I', 'O'],
   'Os': ['O', 'S', 'F', 'Cl', 'Br'],
   'P': ['O', 'S', 'Se', 'F', 'Cl', 'Br', 'N', 'I', 'P', 'As', 'H'],
   'Pa': ['O', 'F', 'Cl', 'Br'],
   'Pb': ['O', 'S', 'Se', 'F', 'Cl', 'Br', 'I', 'N', 'Te', 'P', 'As', 'H'],
   'Pd': ['O', 'S', 'F', 'Cl', 'Br', 'I', 'N', 'C', 'Se', 'Te', 'P', 'As', 'H'],
   'Pm': ['F', 'Cl', 'Br'],
   'Po': ['O', 'F'],
   'Pr': ['O', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'N', 'P', 'As', 'H'],
   'Pt': ['O', 'S', 'F', 'Cl', 'Br', 'C', 'N', 'I', 'Se', 'Te', 'P', 'As', 'H'],
   'Pu': ['O', 'F', 'Cl', 'S', 'Br', 'I'],
   'Rb': ['O', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'N', 'P', 'As', 'H'],
   'Re': ['Cl', 'O', 'F', 'Br', 'I', 'S', 'Se', 'Te', 'N', 'P', 'As', 'H'],
   'Rh': ['O', 'F', 'Cl', 'Br', 'N', 'I', 'S', 'Se', 'Te', 'P', 'As', 'H'],
   'Ru': ['Se', 'F', 'O', 'S', 'Cl', 'N', 'Br', 'I', 'Te', 'P', 'As', 'H'],
   'S': ['O', 'S', 'N', 'F', 'Cl', 'Br', 'I', 'H'],
   'Sb': ['O', 'S', 'Se', 'F', 'Cl', 'Br', 'I', 'N', 'Te', 'P', 'As', 'H'],
   'Sc': ['O', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'N', 'P', 'As', 'H'],
   'Se': ['S', 'Se', 'O', 'F', 'Cl', 'Br', 'N', 'I', 'H'],
   'Si': ['O', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'C', 'N', 'P', 'As', 'H', 'Si'],
   'Sm': ['O', 'N', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'P', 'As', 'H'],
   'Sn': ['O', 'S', 'F', 'Cl', 'Br', 'I', 'N', 'Se', 'Te', 'P', 'As', 'H'],
   'Sr': ['O', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'N', 'P', 'As', 'H'],
   'Ta': ['O', 'S', 'F', 'Cl', 'Br', 'I', 'Se', 'Te', 'N', 'P', 'As', 'H'],
   'Tb': ['O', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'N', 'P', 'As', 'H'],
   'Tc': ['O', 'F', 'Cl'],
   'Te': ['O', 'S', 'F', 'Cl', 'Br', 'I', 'Se', 'Te', 'N', 'P', 'H'],
   'Th': ['O', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'N', 'P', 'As', 'H'],
   'Ti': ['F', 'Cl', 'Br', 'O', 'S', 'I', 'Se', 'Te', 'N', 'P', 'As', 'H'],
   'Tl': ['O', 'S', 'F', 'Cl', 'Br', 'I', 'Se', 'Te', 'N', 'P', 'As', 'H'],
   'Tm': ['O', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'N', 'P', 'As', 'H'],
   'U': ['O', 'S', 'F', 'Cl', 'Br', 'I', 'N', 'Se', 'Te', 'P', 'As', 'H'],
   'V': ['O', 'Cl', 'S', 'F', 'Br', 'N', 'I', 'Se', 'Te', 'P', 'As', 'H'],
   'W': ['O', 'F', 'Cl', 'Br', 'I', 'S', 'Se', 'Te', 'N', 'P', 'As', 'H'],
   'Xe': ['O', 'F'],
   'Y': ['O', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'N', 'P', 'As', 'H'],
   'Yb': ['O', 'N', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'P', 'As', 'H'],
   'Zn': ['O', 'S', 'Se', 'Te', 'F', 'Cl', 'Br', 'I', 'N', 'P', 'As', 'H'],
   'Zr': ['O', 'F', 'Cl', 'S', 'Se', 'Te', 'Br', 'I', 'N', 'P', 'As', 'H']
  }